name: Keep Render Alive

on:
  schedule:
    # Chạy mỗi 14 phút
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -i -sS https://student-club-management-api.onrender.com/health

# Dùng để server render ko tắt
